spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/crud_tienda
spring.datasource.username=guille
spring.datasource.password=guille
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true